// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg91gcxkZ83RH6VAlMNVM0k26_HQSZLlo',
    appId: '1:589158296636:web:b2854b883b8062dbf92739',
    messagingSenderId: '589158296636',
    projectId: 'chat-up-683c7',
    authDomain: 'chat-up-683c7.firebaseapp.com',
    storageBucket: 'chat-up-683c7.appspot.com',
    measurementId: 'G-E6RY37T3CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLe9sfaOAKqbfcsh0tZJTW8VfT_WkxuzM',
    appId: '1:589158296636:android:f502534a8c889766f92739',
    messagingSenderId: '589158296636',
    projectId: 'chat-up-683c7',
    storageBucket: 'chat-up-683c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnDe390_U2EJ3jeaaQF2I1l8CZ49jHmI',
    appId: '1:589158296636:ios:cb3dcded4aa7db26f92739',
    messagingSenderId: '589158296636',
    projectId: 'chat-up-683c7',
    storageBucket: 'chat-up-683c7.appspot.com',
    iosBundleId: 'com.example.chatUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJnDe390_U2EJ3jeaaQF2I1l8CZ49jHmI',
    appId: '1:589158296636:ios:8b3fe3855cd12033f92739',
    messagingSenderId: '589158296636',
    projectId: 'chat-up-683c7',
    storageBucket: 'chat-up-683c7.appspot.com',
    iosBundleId: 'com.example.chatUp.RunnerTests',
  );
}
